### ISSUE TITLE
Error: Cannot find module '/var/task/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb'

### ISSUE THREAD

**Issue by tommiii** [shelfio/aws-lambda-libreoffice#98]
I'm getting this error when I call convertTo, I've installed the package from npm. Any clue?

**Comment by vladgolubev** [comment]
Hey @tommiii, what version of Node are you using?

**Comment by tommiii** [comment]
My lambda runs with node 8.10, if I try locally I get:
`dlopen(/Users/tommi/myProject/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node, 1): no suitable image found.  Did find:
	/Users/tommi/myProject/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00` (working with macOS 10.14.5)

**Comment by vladgolubev** [comment]
What environment are you deploying your project from? Is it local or CI? I guess the environment which installs dependencies and packages lambda artifact archive needs to be Node 8.10 as well

**Comment by tommiii** [comment]
with CI I have Node.js v8.10.0 + NPM 6.1.0

**Comment by tommiii** [comment]
I've found the issue. This package https://www.npmjs.com/package/serverless-plugin-reducer was excluding dependencies

**Comment by iamrahulroy** [comment]
@vladgolubev I'm facing the same issue. I do not have a reducer plugin in my project. Here's the stack trace:

```
Serverless: Failure: dlopen(project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node, 1): no suitable image found.  Did find:
	project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
Error: dlopen(project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node, 1): no suitable image found.  Did find:
	project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/index.js:8:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Promise (project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/index.js:42:17)
    at new Promise (<anonymous>)
    at module.exports.unpack (project_path_truncated/node_modules/@shelf/aws-lambda-brotli-unpacker/src/index.js:13:10)
    at getExecutablePath (project_path_truncated/node_modules/@shelf/aws-lambda-libreoffice/lib/convert.js:24:46)
    at module.exports.libre (project_path_truncated/handler.js:20:26)
    at Promise (project_path_truncated/node_modules/serverless-offline/src/ApiGateway.js:941:17)
    at new Promise (<anonymous>)
    at handler (project_path_truncated/node_modules/serverless-offline/src/ApiGateway.js:540:16)
    at module.exports.internals.Manager.execute (project_path_truncated/node_modules/@hapi/hapi/lib/toolkit.js:41:33)
    at Object.internals.handler (project_path_truncated/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (project_path_truncated/node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (project_path_truncated/node_modules/@hapi/hapi/lib/request.js:312:68)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```

I have tried it with both node 8 & node 10 on OSX.

**Comment by vladgolubev** [comment]
@iamrahulroy this package is compiled to run on Amazon Linux only, it won't run on OSX. If you want to run this part of your project locally, you'll probably need smth like https://github.com/lambci/docker-lambda to reproduce the real Lambda environment with Amazon Linux
